return {
    Regular = {
        m1 = {
            Parry = false,
            Block = true,
            BlockBreak = false,
            BlockBypass = false
        },
        Heavy = {
            Parry = true,
            Block = false,
            BlockBreak = true,
            BlockBypass = false
        },
        Super = {
            Parry = true,
            Block = true,
            BlockBreak = false,
            BlockBypass = false
        }
    }
}