return {
    Regular = {
        m1 = {
            VisualName = "Click",
            Parry = false,
            Block = true,
            BlockBreak = false,
            BlockBypass = false,
            Cooldown = 2
        },
        Heavy = {
            VisualName = "Heavy",
            Parry = true,
            Block = false,
            BlockBreak = true,
            BlockBypass = false,
            Cooldown = 7
        },
        Super = {
            VisualName = "Super",
            Parry = true,
            Block = true,
            BlockBreak = false,
            BlockBypass = false,
            Cooldown = 15
        }
    }
}