name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Selene
        run: |
          wget https://github.com/Kampfkarren/selene/releases/download/0.27.1/selene-0.27.1-linux.zip
          unzip selene-0.27.1-linux.zip
          chmod +x selene
          sudo mv selene /usr/local/bin/

      - name: Run Selene
        id: selene
        run: selene src